title: 成大電機 專題資訊
description: 系學會採訪教授們關於成大電機的專題資訊
author: NCKU EESA

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - post_tutorial.md
